output "public_ip" {
  description = "Public IP address of the tutorial EC2 instance"
  value       = aws_instance.tutorial.public_ip
}

output "ssh_private_key_path" {
  description = "Path of the generated private key"
  value       = local_file.private_key.filename
}

output "inventory_file" {
  description = "Ansible inventory generated by Terraform"
  value       = local_file.ansible_inventory.filename
}

output "inventory_file_yaml" {
  description = "Ansible YAML inventory generated by Terraform"
  value       = local_file.ansible_inventory_yaml.filename
}
